export const employeeConstants = {
  GET_ALL_EMPLOYEES_REQUEST: " GET_ALL_EMPLOYEES_REQUEST",
  GET_ALL_EMPLOYEES_SUCCESS: " GET_ALL_EMPLOYEES_SUCCESS",
  GET_ALL_EMPLOYEES_FAILURE: " GET_ALL_EMPLOYEES_FAILURE",
};
