export const employeeConstants = {
  GET_ALL_EMPLOYEES_REQUEST: " GET_ALL_EMPLOYEES_REQUEST",
  GET_ALL_EMPLOYEES_SUCCESS: " GET_ALL_EMPLOYEES_SUCCESS",
  GET_ALL_EMPLOYEES_FAILURE: " GET_ALL_EMPLOYEES_FAILURE",

  EDIT_EMPLOYEE_REQUEST: "EDIT_EMPLOYEE_REQUEST",
  EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
  EDIT_EMPLOYEE_FALURE: "EDIT_EMPLOYEE_FALURE",
};

export const authConstants = {
  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
};
