export const employeeConstants = {
  GET_ALL_EMPLOYEES_REQUEST: " GET_ALL_EMPLOYEES_REQUEST",
  GET_ALL_EMPLOYEES_SUCCESS: " GET_ALL_EMPLOYEES_SUCCESS",
  GET_ALL_EMPLOYEES_FAILURE: " GET_ALL_EMPLOYEES_FAILURE",

  EDIT_EMPLOYEE_REQUEST: "EDIT_EMPLOYEE_REQUEST",
  EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
  EDIT_EMPLOYEE_FALURE: "EDIT_EMPLOYEE_FALURE",
};
